export const SkillList = [
    "integrating complex design systems",
    "streamlining developer handoffs",
    "aligning design and engineering teams",
    "crafting accessible",
    "scalable UI components",
    "enhancing design-to-development workflows",
    "driving cross-functional alignment",
    "architecting design tokens",
    "prototyping user flows",
    "refining front-end performance",
    "evolving design systems",
    "optimizing component libraries",
    "collaborating on product vision",
    "building reusable components",
    "bridging Figma to code",
    "defining scalable design patterns",
    "optimizing frontend architecture",
    "scaling design systems for global teams",
    "creating developer-friendly workflows",
    "I turn complex challenges into polished solutions.",
    "enhancing CSS architecture",
    "creating robust component libraries",
    "driving alignment across teams",
    "translating high-level concepts into intuitive interfaces",
    "developing scalable styles",
    "mentoring teams on design best practices",
    "implementing AI-driven design workflows to streamline processes and improve collaboration",
    "leveraging AI tools for automated prototyping and rapid iteration of UX/UI designs",
    "integrating AI-powered accessibility testing to ensure inclusive and user-friendly interfaces",
    "optimizing design-to-development handoffs using AI-based tools to generate code from designs",
    "using AI to analyze user behavior data for informed, data-driven design decisions",
    "creating intelligent design systems with adaptive components that adjust based on user needs",
    "enhancing front-end performance by integrating AI-assisted performance optimization tools",
    "automating repetitive design tasks (e.g., color palette generation, layout suggestions) with AI",
    "incorporating AI-powered content generation to support product narrative and UX writing",
    "implementing predictive design insights using machine learning for better product outcomes"
]
